//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourthSource.Staffing.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string WorkPhone { get; set; }
        public string Other { get; set; }
        public Nullable<int> Company { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Company Company1 { get; set; }
    }
}
