//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourthSource.Staffing.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PositionType
    {
        public PositionType()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public int Id { get; set; }
        public string PositionType1 { get; set; }
    
        public virtual ICollection<Request> Requests { get; set; }
    }
}
