//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourthSource.Staffing.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public Request()
        {
            this.RequestCertifications = new HashSet<RequestCertification>();
            this.RequestTechnologies = new HashSet<RequestTechnology>();
        }
    
        public int Id { get; set; }
        public string RequestNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> RequestType { get; set; }
        public Nullable<System.DateTime> DateNeeded { get; set; }
        public Nullable<int> CompanyNeeded { get; set; }
        public Nullable<int> ContactName { get; set; }
        public Nullable<int> PositionType { get; set; }
        public Nullable<int> Lenght { get; set; }
        public Nullable<int> ResourceType { get; set; }
        public string Position { get; set; }
        public Nullable<short> YearsExp { get; set; }
        public Nullable<int> Travel { get; set; }
        public string AddtionalDetails { get; set; }
        public string InternalComments { get; set; }
        public string EnglishLevel { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual PositionType PositionType1 { get; set; }
        public virtual ICollection<RequestCertification> RequestCertifications { get; set; }
        public virtual RequestType RequestType1 { get; set; }
        public virtual ResourceType ResourceType1 { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual ICollection<RequestTechnology> RequestTechnologies { get; set; }
    }
}
