//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourthSource.Staffing.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestCertification
    {
        public int Id { get; set; }
        public int Request { get; set; }
        public string Certification { get; set; }
        public string IssuedBy { get; set; }
        public string Technology { get; set; }
    
        public virtual Request Request1 { get; set; }
    }
}
